# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AdGroupInfo.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='AdGroupInfo.proto',
    package='entity',
    serialized_pb=_b(
        '\n\x11\x41\x64GroupInfo.proto\x12\x06\x65ntity\"\x82\x05\n\x0b\x41\x64GroupInfo\x12\x10\n\x08group_id\x18\x01 \x02(\x03\x12\x13\n\x0b\x63\x61mpaign_id\x18\x02 \x02(\x03\x12\x0c\n\x04name\x18\x03 \x02(\t\x12\x0c\n\x04\x61rea\x18\x04 \x01(\t\x12\x10\n\x08position\x18\x05 \x01(\t\x12\x17\n\x0fgroup_direction\x18\x06 \x01(\t\x12\x14\n\x0c\x63reated_time\x18\x07 \x01(\t\x12\x0e\n\x06\x62udget\x18\x08 \x01(\x03\x12\r\n\x05price\x18\t \x01(\x03\x12\x14\n\x0c\x62illing_type\x18\n \x01(\x05\x12\x10\n\x08put_type\x18\x0b \x01(\x05\x12*\n\x06\x61\x64info\x18\x0c \x03(\x0b\x32\x1a.entity.AdGroupInfo.AdInfo\x12\x30\n\ttimeRange\x18\r \x03(\x0b\x32\x1d.entity.AdGroupInfo.TimeRange\x12\x0e\n\x06status\x18\x0e \x01(\x05\x12\x0b\n\x03pin\x18\x0f \x01(\t\x12\x13\n\x0buser_status\x18\x10 \x01(\x05\x12\x11\n\tuser_type\x18\x11 \x01(\x05\x12\x11\n\tvander_id\x18\x12 \x01(\x03\x12\x15\n\rprovider_code\x18\x13 \x01(\t\x12\x17\n\x0f\x61\x64_group_status\x18\x14 \x01(\x05\x12\x13\n\x0b\x61\x64_group_yn\x18\x15 \x01(\x05\x12\x0f\n\x07user_yn\x18\x16 \x01(\x05\x1as\n\x06\x41\x64Info\x12\x0c\n\x04\x61\x64Id\x18\x01 \x02(\x03\x12\x0e\n\x06\x61\x64Name\x18\x02 \x01(\t\x12\x0e\n\x06imgUrl\x18\x03 \x01(\t\x12\r\n\x05width\x18\x04 \x01(\x05\x12\x0e\n\x06height\x18\x05 \x01(\x05\x12\x0b\n\x03url\x18\x06 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x07 \x01(\t\x1a\'\n\tTimeRange\x12\r\n\x05start\x18\x01 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x03\x42&\n\x16\x63om.jd.flow.index.beanB\x0c\x41\x44GroupProto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ADGROUPINFO_ADINFO = _descriptor.Descriptor(
    name='AdInfo',
    full_name='entity.AdGroupInfo.AdInfo',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='adId', full_name='entity.AdGroupInfo.AdInfo.adId', index=0,
            number=1, type=3, cpp_type=2, label=2,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='adName', full_name='entity.AdGroupInfo.AdInfo.adName', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='imgUrl', full_name='entity.AdGroupInfo.AdInfo.imgUrl', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='width', full_name='entity.AdGroupInfo.AdInfo.width', index=3,
            number=4, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='height', full_name='entity.AdGroupInfo.AdInfo.height', index=4,
            number=5, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='url', full_name='entity.AdGroupInfo.AdInfo.url', index=5,
            number=6, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='content', full_name='entity.AdGroupInfo.AdInfo.content', index=6,
            number=7, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=516,
    serialized_end=631,
)

_ADGROUPINFO_TIMERANGE = _descriptor.Descriptor(
    name='TimeRange',
    full_name='entity.AdGroupInfo.TimeRange',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='start', full_name='entity.AdGroupInfo.TimeRange.start', index=0,
            number=1, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='end', full_name='entity.AdGroupInfo.TimeRange.end', index=1,
            number=2, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=633,
    serialized_end=672,
)

_ADGROUPINFO = _descriptor.Descriptor(
    name='AdGroupInfo',
    full_name='entity.AdGroupInfo',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='group_id', full_name='entity.AdGroupInfo.group_id', index=0,
            number=1, type=3, cpp_type=2, label=2,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='campaign_id', full_name='entity.AdGroupInfo.campaign_id', index=1,
            number=2, type=3, cpp_type=2, label=2,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='name', full_name='entity.AdGroupInfo.name', index=2,
            number=3, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='area', full_name='entity.AdGroupInfo.area', index=3,
            number=4, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='position', full_name='entity.AdGroupInfo.position', index=4,
            number=5, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='group_direction', full_name='entity.AdGroupInfo.group_direction', index=5,
            number=6, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='created_time', full_name='entity.AdGroupInfo.created_time', index=6,
            number=7, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='budget', full_name='entity.AdGroupInfo.budget', index=7,
            number=8, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='price', full_name='entity.AdGroupInfo.price', index=8,
            number=9, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='billing_type', full_name='entity.AdGroupInfo.billing_type', index=9,
            number=10, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='put_type', full_name='entity.AdGroupInfo.put_type', index=10,
            number=11, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='adinfo', full_name='entity.AdGroupInfo.adinfo', index=11,
            number=12, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='timeRange', full_name='entity.AdGroupInfo.timeRange', index=12,
            number=13, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='status', full_name='entity.AdGroupInfo.status', index=13,
            number=14, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='pin', full_name='entity.AdGroupInfo.pin', index=14,
            number=15, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='user_status', full_name='entity.AdGroupInfo.user_status', index=15,
            number=16, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='user_type', full_name='entity.AdGroupInfo.user_type', index=16,
            number=17, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='vander_id', full_name='entity.AdGroupInfo.vander_id', index=17,
            number=18, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='provider_code', full_name='entity.AdGroupInfo.provider_code', index=18,
            number=19, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='ad_group_status', full_name='entity.AdGroupInfo.ad_group_status', index=19,
            number=20, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='ad_group_yn', full_name='entity.AdGroupInfo.ad_group_yn', index=20,
            number=21, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='user_yn', full_name='entity.AdGroupInfo.user_yn', index=21,
            number=22, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[_ADGROUPINFO_ADINFO, _ADGROUPINFO_TIMERANGE, ],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=30,
    serialized_end=672,
)

_ADGROUPINFO_ADINFO.containing_type = _ADGROUPINFO
_ADGROUPINFO_TIMERANGE.containing_type = _ADGROUPINFO
_ADGROUPINFO.fields_by_name['adinfo'].message_type = _ADGROUPINFO_ADINFO
_ADGROUPINFO.fields_by_name['timeRange'].message_type = _ADGROUPINFO_TIMERANGE
DESCRIPTOR.message_types_by_name['AdGroupInfo'] = _ADGROUPINFO

AdGroupInfo = _reflection.GeneratedProtocolMessageType('AdGroupInfo', (_message.Message,), dict(

    AdInfo=_reflection.GeneratedProtocolMessageType('AdInfo', (_message.Message,), dict(
        DESCRIPTOR=_ADGROUPINFO_ADINFO,
        __module__='AdGroupInfo_pb2'
        # @@protoc_insertion_point(class_scope:entity.AdGroupInfo.AdInfo)
    ))
    ,

    TimeRange=_reflection.GeneratedProtocolMessageType('TimeRange', (_message.Message,), dict(
        DESCRIPTOR=_ADGROUPINFO_TIMERANGE,
        __module__='AdGroupInfo_pb2'
        # @@protoc_insertion_point(class_scope:entity.AdGroupInfo.TimeRange)
    ))
    ,
    DESCRIPTOR=_ADGROUPINFO,
    __module__='AdGroupInfo_pb2'
    # @@protoc_insertion_point(class_scope:entity.AdGroupInfo)
))
_sym_db.RegisterMessage(AdGroupInfo)
_sym_db.RegisterMessage(AdGroupInfo.AdInfo)
_sym_db.RegisterMessage(AdGroupInfo.TimeRange)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(),
                                                _b('\n\026com.jd.flow.index.beanB\014ADGroupProto'))
# @@protoc_insertion_point(module_scope)
