# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MediaInfo.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='MediaInfo.proto',
    package='entity',
    serialized_pb=_b(
        '\n\x0fMediaInfo.proto\x12\x06\x65ntity\"\xf0\x01\n\tMediaInfo\x12\x10\n\x08media_id\x18\x01 \x02(\x03\x12\x12\n\nmedia_name\x18\x02 \x02(\t\x12\x12\n\nmedia_type\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x14\n\x0c\x62illing_type\x18\x05 \x01(\x05\x12\r\n\x05width\x18\x06 \x01(\x05\x12\x0e\n\x06height\x18\x07 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x08 \x01(\t\x12\x13\n\x0bspread_type\x18\t \x01(\x05\x12\x14\n\x0cpublish_type\x18\n \x01(\x05\x12\x10\n\x08put_type\x18\x0b \x01(\x05\x12\r\n\x05\x61\x64_id\x18\x0c \x01(\x03\x12\n\n\x02yn\x18\r \x01(\x05\x42$\n\x16\x63om.jd.flow.index.beanB\nMediaProto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_MEDIAINFO = _descriptor.Descriptor(
    name='MediaInfo',
    full_name='entity.MediaInfo',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='media_id', full_name='entity.MediaInfo.media_id', index=0,
            number=1, type=3, cpp_type=2, label=2,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='media_name', full_name='entity.MediaInfo.media_name', index=1,
            number=2, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='media_type', full_name='entity.MediaInfo.media_type', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='url', full_name='entity.MediaInfo.url', index=3,
            number=4, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='billing_type', full_name='entity.MediaInfo.billing_type', index=4,
            number=5, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='width', full_name='entity.MediaInfo.width', index=5,
            number=6, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='height', full_name='entity.MediaInfo.height', index=6,
            number=7, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='content', full_name='entity.MediaInfo.content', index=7,
            number=8, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='spread_type', full_name='entity.MediaInfo.spread_type', index=8,
            number=9, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='publish_type', full_name='entity.MediaInfo.publish_type', index=9,
            number=10, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='put_type', full_name='entity.MediaInfo.put_type', index=10,
            number=11, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='ad_id', full_name='entity.MediaInfo.ad_id', index=11,
            number=12, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='yn', full_name='entity.MediaInfo.yn', index=12,
            number=13, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=28,
    serialized_end=268,
)

DESCRIPTOR.message_types_by_name['MediaInfo'] = _MEDIAINFO

MediaInfo = _reflection.GeneratedProtocolMessageType('MediaInfo', (_message.Message,), dict(
    DESCRIPTOR=_MEDIAINFO,
    __module__='MediaInfo_pb2'
    # @@protoc_insertion_point(class_scope:entity.MediaInfo)
))
_sym_db.RegisterMessage(MediaInfo)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(),
                                                _b('\n\026com.jd.flow.index.beanB\nMediaProto'))
# @@protoc_insertion_point(module_scope)
